joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

velocity_controller:
  joint: r1_prismatic
  type: velocity_controllers/JointVelocityController
  # pid: {p: 100.0, i: 0.1, d: 10.0}

# velocity_controller_2:
#   joint: r2_prismatic
#   type: effort_controllers/JointEffortController